server {
    listen 80 default_server;

    root /var/www/html/Web;

    location / {
        if ($request_uri !~ "^/Web(/|$)") {
            return 301 /Web$uri;
        }

        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        include /opt/docker/etc/nginx/php.conf;
    }
}
